
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Kalamu\MenuServiceBundle\Menu\MenuBuilder:
        class: Kalamu\MenuServiceBundle\Menu\MenuBuilder
        arguments:
            $config: '%kalamu_menu_service.menus%'
